### PR TITLE
python2 demo notebook for openrefine-client and some updates

### PR DESCRIPTION
**Pull request by felixlohmeier**
* updated openrefine-client from 0.3.4 to 0.3.7
* improved bash demo notebook for openrefine-client
* added python2 kernel
* added python2 demo notebook for openrefine-client
* pinned versions for nbserverproxy and bash_kernel

### CODE REVIEW

**Comment by betatim** [comment]
https://mybinder.org/v2/gh/felixlohmeier/openrefineder/python2 to launch this PR on mybinder.org (I wanted to try out the notebooks before pressing merge, need to come back to this in a bit)

**Comment by felixlohmeier** [comment]
Having a second look, I forgot to update the download URL in `postBuild`. Fixed with https://github.com/betatim/openrefineder/pull/11/commits/3045584e8e4b85c5278620cc36dbf86012006175

The bash demo notebook `openrefine-client-bash.ipynb` worked anyway, because step `In [2]` overwrites the pre-installed file.

**Comment by betatim** [comment]
```python
if 'openrefineder' in os.environ['HOSTNAME']:
    notebook = !jupyter notebook list | grep -o -E 'http\S+'
    openrefine_url = notebook[0].replace('?token', 'openrefine?token')
    from urllib import urlopen
    from time import sleep
    for i in range(30):
        response = urlopen(openrefine_url).read()
        sleep(1)
        if 'openrefine' in response:
            openrefine_url = openrefine_url.replace('http://0.0.0.0:8888','https://hub.gke.mybinder.org')
            print('OpenRefine is available at %s' % openrefine_url)
            break
        if i == 30:
            print('timeout')
```

Do you need this code? In particular the bit that hard codes `hub.gke.mybinder.org` won't work when the repo gets launched on our other cluster.

I'd try writing the URL as a relative URL so only the part after the hostname `OpenRefine is available <a href="/blah/foo>here</a>`. We'd either have to wrap the output of this cell so that it gets displayed as HTML or you can add this link into a markdown cell (because it will always be the same?).

**Comment by felixlohmeier** [comment]
I would like to give the user a command to start OpenRefine directly from the notebook to support "Run all cells" without errors. I found a solution to print the relative path but the code looks a bit ugly:

in:
```python
import os
if 'openrefineder' in os.environ['HOSTNAME']:
    notebook = !jupyter notebook list | grep -o -E 'http\S+'
    openrefine_url = notebook[0].replace('?token', 'openrefine?token')
    from urllib import urlopen
    from time import sleep
    for i in range(30):
        response = urlopen(openrefine_url).read()
        sleep(1)
        if 'openrefine' in response:
            openrefine_url = openrefine_url.replace('http://0.0.0.0:8888','')
            from IPython.core.display import display, HTML
            display(HTML('OpenRefine is available at ' + '<a href="' +
                         openrefine_url + '">' + openrefine_url + '</a>'))
            break
        if i == 30:
            print('timeout')
```
out:
OpenRefine is available at [/user/felixlohmeier-openrefineder-h55qfuwu/openrefine?token=zoUJqNZ8RUeCThvPxmKvog](https://hub.gke.mybinder.org/user/felixlohmeier-openrefineder-h55qfuwu/openrefine?token=zoUJqNZ8RUeCThvPxmKvog)

**Comment by betatim** [comment]
Ah! Didn't realise the bit about starting openrefine for people. What do you think of:
```python
display(HTML('<a href="' + openrefine_url + '">Click here to open OpenRefine</a>'))
```
to give it a nicer name?

Otherwise I'd be happy to merge it as is if you are happy.

**Comment by felixlohmeier** [comment]
Yeah, sounds (and looks( better! :+1:  Thank you for your enhancements!

**Comment by betatim** [comment]
No worries and thanks for all the work on making this repo more than just a quick demo!

**Pull request merged**
