### PR TITLE
replace nbopenrefineproxy with jupyter-server-proxy

### PR DESCRIPTION
**Pull request by felixlohmeier**
* resolves issue #7 New `jupyter-server-proxy` setup
* follows https://github.com/psychemedia/jupyterserverproxy-openrefine/ in general but added autolaunch of OpenRefine with https://github.com/felixlohmeier/openrefineder/blob/aea870da0ee937a3edd9c9bbb30fa174234dc009/binder/start

### CODE REVIEW

**Comment by felixlohmeier** [comment]
I just noticed that I had not yet adjusted the new directory structure ("notebooks") in the README. I have done that now: https://github.com/betatim/openrefineder/pull/15/commits/6711f3a82e14e11ca4806fc6f7cf51669e4d99a8

**Comment by betatim** [comment]
Thanks for this! Looks good to me and seems to work (gave it a spin on mybinder.org). One thing I realised is that I don't know how to access JupyterLab with this setup. I wanted to go there to see if the "launcher tiles" still show up.

**Comment by felixlohmeier** [comment]
> One thing I realised is that I don't know how to access JupyterLab with this setup. I wanted to go there to see if the "launcher tiles" still show up.

@psychemedia added [this line](https://github.com/psychemedia/jupyterserverproxy-openrefine/blob/e0af77395d4cb20309962a2a77c28084629cf0c6/binder/postBuild#L19) to the postBuild in [his repo](https://github.com/psychemedia/jupyterserverproxy-openrefine):
```
jupyter labextension install jupyterlab-server-proxy
```

Shall I add that to the pull request?

**Comment by betatim** [comment]
I tried to run/build https://github.com/psychemedia/jupyterserverproxy-openrefine but it fails with
```
......
Step 47/51 : RUN chmod +x binder/postBuild
 ---> Running in 29c147267364
Removing intermediate container 29c147267364
 ---> 8f74510c102e
Step 48/51 : RUN ./binder/postBuild
 ---> Running in 241a6495f338
An error occured.
ValueError: The extension "jupyterlab-server-proxy" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.2.0 <2.3.0          >=0.19.1 <0.20.0@jupyterlab/application
>=2.2.0 <2.3.0          >=0.19.1 <0.20.0@jupyterlab/launcher
See the log file for details:  /tmp/jupyterlab-debug-fj8wn_dg.log
Removing intermediate container 241a6495f338
The command '/bin/sh -c ./binder/postBuild' returned a non-zero code: 1
```

Looks like it is more tricky than just adding that line (I guess)?

**Comment by betatim** [comment]
Merged as is, I think figuring out jupyter lab support is worth doing in a new PR (if someone has time available to work on it).

**Comment by psychemedia** [comment]
Would pinning the version of `jupyterlab-server-proxy` help? Is there a way to script what version it would need to be for the available version of jupyterlab?

**Comment by felixlohmeier** [comment]
> Would pinning the version of `jupyterlab-server-proxy` help? Is there a way to script what version it would need to be for the available version of jupyterlab?

Hi @psychemedia, see https://github.com/betatim/openrefineder/pull/16 :-)

**Comment by psychemedia** [comment]
@felixlohmeier :-)

**Pull request merged**
